Fix bug in eval.pyj for Windows that causes errors
Change the placeholder filename `<argv>.pyj` to `__eval__.pyj`.

Windows file system doesn't allow "<" characters in filenames,
so eval.pyj breaks with the error:

```
java.nio.file.InvalidPathException: Illegal char <<> at index 0:
<argv>.pyj
```