Add script filename, source location to exceptions
E.g.
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "this.object" is null
        at Game.release_piece(server.pjn:762)
        at Game.play(server.pjn:595)
        at <>.on_animate_player(server.pjn:817)
        at net.minescript.interpreter.Script$BoundMethod.call(Script.java:3290)
        ...